=== chuston/impeachment/ToulminV0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:ar="http://argument.chuston.net/v0/argument"
	targetNamespace="http://argument.chuston.net/v0/argument"
	elementFormDefault="qualified">

	<xs:complexType name="subjectType">
		<xs:annotation>
			<xs:documentation>
				<![CDATA[
				A person, place, or thing with a discrete identity.
				 ]]>
			</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="subid"
					use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="eventType">
		<xs:annotation>
			<xs:documentation>Represents an event in time. Intended to track
				items against time.
			</xs:documentation>
		</xs:annotation>
		<xs:complexContent mixed="true">
			<xs:extension base="xs:anyType">

				<xs:attribute name="eventid" type="xs:string" use="required" />
				<xs:attribute name="pit" type="xs:dateTime" use="required">
					<xs:annotation>
						<xs:documentation>A point in time to tie to a time line. Do I need
							ranges?
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:element name="eventref">
		<xs:complexType>
			<xs:attribute name="eventid" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="question">
		<xs:complexType mixed="true">
			<xs:complexContent>
				<xs:extension base="xs:anyType">
					<xs:attribute name="qid" type="xs:integer" use="optional" />
					<xs:attribute name="answer" type="xs:integer" use="optional" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="note">
		<xs:complexType mixed="true">
			<xs:complexContent>
				<xs:extension base="xs:anyType">
					<xs:attribute name="nid" type="xs:integer" use="optional" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="claimType">
		<xs:sequence>
			<xs:element ref="ar:subref" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>Used to tag a claim with topics</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element ref="ar:note" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="assert" minOccurs="1">
				<xs:complexType mixed="true">
					<xs:complexContent>
						<xs:extension base="xs:anyType"></xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="warrant" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType mixed="true">
					<xs:sequence>
						<xs:element name="desc" minOccurs="0">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="xs:anyType" />
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
						<xs:element ref="ar:dataref"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="refutation" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType mixed="true">
					<xs:sequence>
						<xs:element name="desc" minOccurs="0">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="xs:anyType" />
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
						<xs:element ref="ar:claimref" />		
					</xs:sequence>
				</xs:complexType>							
			</xs:element>
		</xs:sequence>
		<xs:attribute name="claimid" type="xs:string"
			use="required" />
		<xs:attribute name="source" type="xs:string" use="optional" />
	</xs:complexType>
	
	<xs:element name="claimref">
		<xs:complexType>
			<xs:attribute name="claimid" type="xs:string"
				use="required" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="dataType">
		<xs:complexContent mixed="true">
			<xs:extension base="xs:anyType">
				<xs:attribute name="did" type="xs:string"
					use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="DataRefType">
		<xs:attribute name="did" type="xs:string" use="required" />
	</xs:complexType>
	
	<xs:element name="dataref" type="ar:DataRefType" />

	<xs:complexType name="subjectList">
		<xs:sequence>
			<xs:element name="subject" type="ar:subjectType"
				minOccurs="0" maxOccurs="unbounded" />

		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="eventList">
		<xs:sequence>
			<xs:element name="event" type="ar:eventType" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="dataList">
		<xs:sequence>
			<xs:element name="data" type="ar:dataType" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="claimList">
		<xs:sequence>
			<xs:element name="claim" type="ar:claimType" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="subref">
		<xs:complexType>
			<xs:attribute name="subid" type="xs:string"
				use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="argument">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="subjects" type="ar:subjectList"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="events" type="ar:eventList"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="datas" type="ar:dataList" minOccurs="1" />
				<xs:element name="claims" type="ar:claimList"
					minOccurs="1" />
			</xs:sequence>
			<xs:attribute name="argid" />
			<xs:attribute name="title" />
			<xs:attribute name="version" />
		</xs:complexType>

		<!-- keys and references -->
		<xs:unique name="claim-key">
			<xs:selector xpath=".//ar:claim" />
			<xs:field xpath="@claimid" />
		</xs:unique>
		
		<xs:unique name="subject-key">
			<xs:selector xpath="./ar:subjects/ar:subject" />
			<xs:field xpath="@subid"></xs:field>
		</xs:unique>
		
		<xs:unique name="data-key">
			<xs:selector xpath="./ar:datas/ar:data" />
			<xs:field xpath="@did" />
		</xs:unique>

		<xs:unique name="event-key">
			<xs:selector xpath="./ar:events/ar:event" />
			<xs:field xpath="@eventid" />
		</xs:unique>

		<xs:keyref name="subject-fk" refer="ar:subject-key">
			<xs:selector xpath=".//ar:subref" />
			<xs:field xpath="@subid" />
		</xs:keyref>
		
		<xs:keyref name="source-fk" refer="ar:event-key">
			<xs:selector xpath=".//ar:claim" />
			<xs:field xpath="@source"/>
		</xs:keyref>

		<xs:keyref name="event-fk" refer="ar:event-key">
			<xs:selector xpath=".//ar:eventref" />
			<xs:field xpath="@eventid"/>
		</xs:keyref>

		<xs:keyref name="data-fk" refer="ar:data-key">
			<xs:selector xpath=".//ar:dataref" />
			<xs:field xpath="@did" />
		</xs:keyref>
		
		<xs:keyref name="claim-fk" refer="ar:claim-key">
			<xs:selector xpath=".//ar:claimref" />
			<xs:field xpath="@claimid" />
		</xs:keyref>
	</xs:element>

</xs:schema>

=== chuston/impeachment/Impeach_20191210.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="ImpeachStyle.xsl" title="WebPage" type="text/xsl"?>

<ar:argument argid="impeachment" version="2019-12-10" title="Impeachment Review"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:ar="http://argument.chuston.net/v0/argument"
	xsi:schemaLocation="http://argument.chuston.net/v0/argument Toulminv0.xsd">
	<ar:subjects>
		<ar:subject subid="djt">Donald J. Trump</ar:subject>
		<ar:subject subid="ltcvindman">Lt Col Vindman, NSC expert on Ukraine</ar:subject>
		<ar:subject subid="vz">Volodymir Zelenski, President of Ukraine</ar:subject>
		<ar:subject subid="cnn">CNN (news outlet)</ar:subject>
		<ar:subject subid="rg">Rudy Guliani</ar:subject>
		<ar:subject subid="dg">Daniel Goldman (House Intel Committee Staffer/Lawyer)</ar:subject>
		<ar:subject subid="ur-aid">$391 million of Congressionally appropriated military aid</ar:subject>
		<ar:subject subid="wh">White House Staff</ar:subject>
		<ar:subject subid="wh-meeting">White House Oval Office meeting</ar:subject>
		<ar:subject subid="vp">Vladimir Putin</ar:subject>
		<ar:subject subid="ica">Impoundment Control Act of 1974</ar:subject>
		<ar:subject subid="hic">House Intel Committee</ar:subject>
		<ar:subject subid="jb">Joe Biden</ar:subject>
		<ar:subject subid="burisma">Burisma</ar:subject>
		<ar:subject subid="hb">Hunter Biden</ar:subject>
		<ar:subject subid="intel-report">The Trump Ukraine Impeachment Inquiry Report</ar:subject>
		<ar:subject subid="uei">Ukrainian Election Interference</ar:subject>
		<ar:subject subid="ob">Obstruction</ar:subject>
		<ar:subject subid="natsec">National Security</ar:subject>
		<ar:subject subid="gs">Gordon Sondland</ar:subject>
		<ar:subject subid="ay">Andrey Yerkmak</ar:subject>
		<ar:subject subid="kv">Kurt Volker</ar:subject>
		<ar:subject subid="crowdstrike">US company that did forensics on hacked DNC server.</ar:subject>
		<ar:subject subid="biden_inv">Investigation in Hunter Biden's relationship with Burisma and Joe Bidens role in firing Shokin.</ar:subject>
		<ar:subject subid="shokin">Viktor Shokin</ar:subject>
		<ar:subject subid="interfere2016">Interference in 2016 election</ar:subject>
		<ar:subject subid="fiona">Fiona Hill</ar:subject>
		<ar:subject subid="mueller">Robert Mueller</ar:subject>
		<ar:subject subid="mueller-rept">Mueller Report</ar:subject>
		<ar:subject subid="bolton">John Bolton</ar:subject>
		<ar:subject subid="d-holmes">David Holmes</ar:subject>
	</ar:subjects>

	<ar:events>
		<ar:event eventid="2016elec" pit="2016-11-08T00:00:00-06:00">2016 U.S. election</ar:event>
		<ar:event eventid="apr10call" pit="2019-04-10T00:00:00-06:00">April 10th call between <ar:subref subid="djt"/> and <ar:subref subid="vz"/></ar:event>
		<ar:event eventid="jul25call" pit="2019-07-25T00:00:00-06:00">July 25th call between <ar:subref subid="djt"/> and <ar:subref subid="vz"/></ar:event>
		<ar:event eventid="jul26kyiv-meetings" pit="2019-07-26T00:00:00-06:00">US Officials met with <ar:subref subid="vz"/> and other Ukrainian officials in Kyiv.</ar:event>
		<ar:event eventid="jul26-gs-ay" pit="2019-07-26T00:00:00-06:00"><ar:subref subid="gs"/> has a private one-on-one meeting with <ar:subref subid="ay"/> at  <ar:subref subid="ay"/>'s office.</ar:event>
		<ar:event eventid="jul26-gs-dh-lunch" pit="2019-07-26T00:00:00-06:00"><ar:subref subid="gs"/> takes <ar:subref subid="d-holmes"/> and two other Dept of State employees to lunch.</ar:event>
		<ar:event eventid="sond_jul25" pit="2019-07-25T00:00:00-06:00"><ar:subref subid="djt"/> and <ar:subref subid="gs"/> talk by phone &quot;just prior&quot; to <ar:eventref eventid="jul25call"/></ar:event>
		<ar:event eventid="volker-yermak-txt" pit="2019-07-25T08:36:00-06:00">July 25th text from <ar:subref subid="kv"/> to <ar:subref subid="ay"/> stating &quot;Heard from White House - assuming President Z convinces trump he will investivate / get to the bottom of what happened in 2016, we will nail down date for visit to Washington.&quot;</ar:event>
		<ar:event eventid="20191209-dg-hjc" pit="2019-12-09T00:00:00-06:00"><ar:subref subid="dg"/> testimony to House Judiciary committee (https://www.c-span.org/video/?467123-1/hearing-evidence-impeachment-inquiry)</ar:event>
		<ar:event eventid="20191119-ltcvinman" pit="2019-11-19T00:00:00-06:00"><ar:subref subid="ltcvindman"/> testifies to <ar:subref subid="hic"/></ar:event>
		<ar:event eventid="20191119-hill-holmes" pit="2019-11-19T00:00:00-06:00"><ar:subref subid="fiona"/> and <ar:subref subid="d-holmes"/> testify to <ar:subref subid="hic"/></ar:event>
		<ar:event eventid="20191120-gs-hit" pit="2019-11-20T00:00:00-06:00"><ar:subref subid="gs"/> testifies to <ar:subref subid="hic"/></ar:event>
		<ar:event eventid="djt2016inaug" pit="2016-01-20T00:00:00-06:00">Inauguration of <ar:subref subid="djt"/> as 45th President of the United States</ar:event>
		<ar:event eventid="vp-orban-20170202" pit="2017-02-02T00:00:00-06:00">Joint press conference with <ar:subref subid="vp"/> and Prime Minister Orban</ar:event>
		<ar:event eventid="vp-npr-20191127" pit="2019-11-27T00:00:00-06:00"><ar:subref subid="vp"/> interview with NPR, &quot;The View from Moscow on the Trump Impeachment Inquiry&quot;</ar:event>
	</ar:events>
	
	<ar:datas>
		<ar:data did="100">On April 10?, 2019, <ar:subref subid="rg"/> appeared on <ar:subref subid="cnn"/> and claimed he was &quot;interfering in an investigation&quot;</ar:data>
		<ar:data did="200">July 25th &quot;Memorandum of Telephone Conversation&quot; between <ar:subref subid="djt"/> and <ar:subref subid="vz"/>. (https://games-cdn.washingtonpost.com/notes/prod/default/documents/d2311f4f-a767-4ddc-868b-8bc9af8226c5/note/339b784b-719c-464f-9eda-85daede53092.pdf)</ar:data>
		<ar:data did="300"><ar:subref subid="burisma"/> is a Ukrainian energy company widely suspected of corrupt acts. <ar:question>what acts? detail?</ar:question></ar:data>
		<ar:data did="400"><ar:subref subid="gs"/> donated $1,000,000 to <ar:subref subid="djt"/>'s inauguration fund.</ar:data>
		<ar:data did="410"><ar:subref subid="gs"/> was directed by <ar:subref subid="djt"/> himself to take on a leading role in Ukrainian issues.</ar:data>
		<ar:data did="420"><ar:subref subid="gs"/> is the ambassador to the European Union</ar:data>
		<ar:data did="500"><ar:subref subid="ay"/> is the top aid to <ar:subref subid="vz"/></ar:data>
		<ar:data did="600"><ar:subref subid="gs"/> testified there was a quid-quo-pro during <ar:eventref eventid="20191120-gs-hit"/></ar:data>
		<ar:data did="700">Report: Assessing Russian Activities and Intentions in the Recent US Elections (https://www.documentcloud.org/documents/3254239-Russia-Hacking-report.html)</ar:data>
		<ar:data did="710"><ar:subref subid="mueller"/> testified that the Russian government interfered in the 2016 Presidential election in sweeping and systematic fashion.</ar:data>
		<ar:data did="720"><ar:subref subid="mueller"/> indicted 12 Russian GRU members (http://cdn.cnn.com/cnn/2018/images/07/13/gru.indictment.pdf)</ar:data>
		<ar:data did="800"><ar:subref subid="fiona"/> is an expert on Russia and <ar:subref subid="vp"/></ar:data>
		<ar:data did="900">During <ar:eventref eventid="vp-orban-20170202"/>, <ar:subref subid="vp"/> said &quot;Second, as we all know, during the presidential campaign in the United States, the Ukrainian government adopted a unilateral position in favor of one candidate. â€¦ More than that, certain oligarchs, certainly with the approval of the political leadership, funded this candidate, or female candidate to be more precise.&quot;</ar:data>
		<ar:data did="910">During <ar:eventref eventid="vp-npr-20191127"/><ar:subref subid="vp"/> said &quot;Thank god no one is accusing us anymore of interfering in the U.S. elections. Now they're accusing Ukraine.&quot;</ar:data>
		<ar:data did="1000">Transcript of <ar:eventref eventid="jul25call"/></ar:data>
		<ar:data did="1100">During <ar:eventref eventid="20191120-gs-hit"/>, <ar:subref subid="gs"/> testified &quot;Mr. Giuliani was expressing the desires of the President of the United States, and we knew these investigations were important to the President</ar:data>
		<ar:data did="1200"><ar:subref subid="bolton"/> said <ar:subref subid="rg"/> is a &quot;hand grenade that is going to blow everybody up.&quot;</ar:data>
		<ar:data did="1300">From <ar:dataref did="1000"/>, <ar:subref subid="vz"/> said &quot;I also wanted to thank you for your invitation to visit the United States, specifically Washington DC. On the other hand, I also want to ensure you that we will be very serious about the case and will work on the investigation.&quot;</ar:data>
		<ar:data did="2010"><ar:subref subid="shokin"/> was the Prosecutor General of Ukraine from 2015-02-10 to 2016-02-16.</ar:data>
		<ar:data did="2020"><ar:subref subid="shokin"/> was forced to resign when <ar:subref subid="jb"/>, then VP of US, threatened to withhold $1BB in aid.</ar:data>
		<ar:data did="2030"><ar:subref subid="d-holmes"/> was a senior official at the US Embassy in Ukraine.</ar:data>
		<ar:data did="2040">During <ar:eventref eventid="20191119-hill-holmes"/> (Page 23 of Transcript), <ar:subref subid="d-holmes"/> said &quot;It is important to understand that a White House visit was critical to <ar:subref subid="vz"/>. <ar:subref subid="vz"/> needed to show U.S. support at the highest levels in order to demonstrate to <ar:subref subid="vp"/> that he had U.S. backing as well as to advance his ambitious anti-corruption reform agenda at home.&quot; </ar:data>
		<ar:data did="2050">
			During <ar:eventref eventid="20191119-hill-holmes"/>, <ar:subref subid="d-holmes"/> recounts conversation between <ar:subref subid="gs"/> 
			and <ar:subref subid="djt"/> at <ar:eventref eventid="jul26-gs-dh-lunch"/>:
			&quot;I heard <ar:subref subid="gs"/> greet <ar:subref subid="djt"/> and explain he was calling from Kyiv. I heard President Trump then clarify
